apiVersion: v1
kind: Service
metadata:
  name: {{.Values.deployment.name}}
  labels:
    run: {{.Values.deployment.name}}
spec:
  ports:
  - port: {{.Values.service.port}}
  selector:
    run: {{.Values.deployment.name}}